MMA-6406 added TLS into MQ
navikt/dokdistdpi-2 pull request #50
Opened 2022-10-06 07:16 UTC by tsigab

2022-10-06 10:49 UTC, joakibj requested changes
Har en kommentar ellers ser det greit ut

2022-10-06 10:49 UTC, joakibj commented on dokdistdpi-java-opts.sh
> +JAVA_OPTS="${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=nais"
Ser ingen endringer i `Dockerfile` ?

2022-10-07 09:45 UTC, joakibj approved these changes

2022-10-07 09:45 UTC, joakibj commented on dokdistdpi-java-opts.sh
> +JAVA_OPTS="${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=nais"
Savner `-Xmx` fra `Dockerfile`

2022-10-07 09:57 UTC, avoldsund approved these changes

2022-10-07 10:19 UTC, merged