MMA-6697 lagret varselmeldinger til dokdist database
navikt/dokdistdpi-2 pull request #60
Opened 2023-03-03 13:53 UTC by tsigab

2023-03-03 14:19 UTC, avoldsund requested changes
Har litt kommentarar og forslag :)

2023-03-03 14:19 UTC, avoldsund commented on core/src/main/java/no/nav/dokdistdpi/consumer/rdist001/AdministrerForsendelseConsumer.java
> +	public void oppdaterVarselInfo(OppdaterVarselInfoRequest oppdaterVarselInfo) {
Hadde vore topp viss nye endepunkt blei tatt med webclient, azure og gjekk mot dokdistadmin. Her går det vel mot dokumentdistribusjon med basicauth? Dokdistdittnav har implementert oppdatervarselinfo mot dokdistadmin

2023-03-03 14:19 UTC, avoldsund commented on core/src/main/java/no/nav/dokdistdpi/consumer/rdist001/map/OppdaterVarselInfoMapper.java
> +		Set<Notifikasjon> notifikasjons = new HashSet<>();
```suggestion
		Set<Notifikasjon> notifikasjoner = new HashSet<>();
```

2023-03-03 14:19 UTC, avoldsund commented on core/src/main/java/no/nav/dokdistdpi/consumer/dpi/DpiMeldingsformidler.java
> +		if (SENDT.equals(forsendelseStatusResponse.getStatus()) || OPPRETTET.equals(forsendelseStatusResponse.getStatus())) {
Blir det litt dobbel sjekking av status her og på linje 86?

2023-03-03 14:19 UTC, avoldsund commented on core/src/test/java/no/nav/dokdistdpi/consumer/rdist001/map/OppdaterVarselInfoMapperTest.java
> +		List<Notifikasjon> notifikasjons = oppdaterVarselInfo.notifikasjoner().stream()
```suggestion
		List<Notifikasjon> notifikasjoner = oppdaterVarselInfo.notifikasjoner().stream()
```

2023-03-03 14:19 UTC, avoldsund commented on core/src/test/java/no/nav/dokdistdpi/consumer/rdist001/map/OppdaterVarselInfoMapperTest.java
> +
Kanskje greit å hente ut notifikasjoner.get(0) og notifikasjoner.get(1) som variablar?

2023-03-03 14:19 UTC, avoldsund commented on core/src/test/java/no/nav/dokdistdpi/consumer/rdist001/map/OppdaterVarselInfoMapperTest.java
> +	public void shouldMapEpostVarselTittelWhenDistribusjonsTypeIsVedtakOrViktig() {
Kan ein ha ein parametrisert test som kombinerer denne testen og dei to neste?

2023-03-06 08:32 UTC, tsigab commented on core/src/test/java/no/nav/dokdistdpi/consumer/rdist001/map/OppdaterVarselInfoMapperTest.java
> +	public void shouldMapEpostVarselTittelWhenDistribusjonsTypeIsVedtakOrViktig() {
Endret testen til å bruke _ParameterizedTest_

2023-03-06 08:34 UTC, tsigab commented on core/src/main/java/no/nav/dokdistdpi/consumer/dpi/DpiMeldingsformidler.java
> +		if (SENDT.equals(forsendelseStatusResponse.getStatus()) || OPPRETTET.equals(forsendelseStatusResponse.getStatus())) {
Ja, Det stemmer og skal endre med logikken.

2023-03-06 08:42 UTC, tsigab commented on core/src/main/java/no/nav/dokdistdpi/consumer/rdist001/AdministrerForsendelseConsumer.java
> +	public void oppdaterVarselInfo(OppdaterVarselInfoRequest oppdaterVarselInfo) {
Dokdistdpi-2 konsumerer alle tjenester i dokumentdistribusjon og at det er lurte å migrere WebClient, Azure og tjenester samtidig når migrering til dokdistadmin er fullført.

2023-03-06 09:03 UTC, joakibj requested changes

2023-03-06 09:03 UTC, joakibj commented on core/src/main/java/no/nav/dokdistdpi/consumer/rdist001/map/OppdaterVarselInfoMapper.java
> +	public static final String VARSELTITTEL_VEDTAK = "Varsel om post";
```suggestion
	public static final String EPOST_VARSELTITTEL_VEDTAK = "Varsel om post";
```

2023-03-06 09:03 UTC, joakibj commented on core/src/main/java/no/nav/dokdistdpi/consumer/rdist001/map/OppdaterVarselInfoMapper.java
> +	public static final String VARSELTITTEL_ANNET = "Du har en ny melding";
```suggestion
	public static final String EPOST_VARSELTITTEL_ANNET = "Du har en ny melding";
```

2023-03-06 09:03 UTC, joakibj commented on core/src/main/java/no/nav/dokdistdpi/consumer/dpi/DpiMeldingsformidler.java
> +		if (SENDT.equals(forsendelseStatusResponse.getStatus()) || OPPRETTET.equals(forsendelseStatusResponse.getStatus())) {
Se heller `DokdistAdministrerForsendelseUpdater` for å unngå side effects i denne klassen (skal kun sende til DPI)

2023-03-06 09:12 UTC, tsigab commented on core/src/main/java/no/nav/dokdistdpi/consumer/dpi/DpiMeldingsformidler.java
> +								AppCertificate appCertificate, DpiClient dpiClient,
Det brukt nytt linje.

2023-03-06 09:17 UTC, tsigab commented on core/src/main/java/no/nav/dokdistdpi/consumer/rdist001/map/OppdaterVarselInfoMapper.java
> +	public static final String VARSELTITTEL_ANNET = "Du har en ny melding";
Det rettet navn.

2023-03-06 09:17 UTC, tsigab commented on core/src/main/java/no/nav/dokdistdpi/consumer/rdist001/map/OppdaterVarselInfoMapper.java
> +	public static final String VARSELTITTEL_VEDTAK = "Varsel om post";
Fikset navn.

2023-03-06 12:28 UTC, tsigab commented on core/src/test/java/no/nav/dokdistdpi/consumer/rdist001/map/OppdaterVarselInfoMapperTest.java
> +		List<Notifikasjon> notifikasjons = oppdaterVarselInfo.notifikasjoner().stream()
Takk, AssertJ har veldig mye funksjonalitet for å validere test result.

2023-03-06 12:32 UTC, tsigab commented on core/src/main/java/no/nav/dokdistdpi/consumer/dpi/DpiMeldingsformidler.java
> +		if (SENDT.equals(forsendelseStatusResponse.getStatus()) || OPPRETTET.equals(forsendelseStatusResponse.getStatus())) {
Dette flyttet til DokdistAdministrerForsendelseUpdater og kallt inne camel route.

2023-03-06 12:33 UTC, tsigab commented on core/src/test/java/no/nav/dokdistdpi/consumer/rdist001/map/OppdaterVarselInfoMapperTest.java
> +	private static final String VEDTAK_TEKST = "Du har fått et vedtak fra NAV. Les det i din digitale postkasse.";
De flyttet constant til egen klass.

2023-03-06 15:05 UTC, joakibj requested changes

2023-03-06 15:05 UTC, joakibj commented on core/src/main/java/no/nav/dokdistdpi/consumer/rdist001/AdministrerForsendelseConsumer.java
> +	public void oppdaterVarselInfo(OppdaterVarselInfoRequest oppdaterVarselInfo) {
Dette MÅ endres til dokdistadmin siden det støtter den oppdaterte logikken til `oppdaterVarselInfo`. Samme operasjon på dokumentdistribusjon vil feile!

2023-03-06 15:05 UTC, joakibj requested changes

2023-03-06 15:05 UTC, joakibj commented on core/src/main/java/no/nav/dokdistdpi/consumer/rdist001/AdministrerForsendelseConsumer.java
> +	public void oppdaterVarselInfo(OppdaterVarselInfoRequest oppdaterVarselInfo) {
@tsigab Dessverre så vil ikke den strategien fungere

2023-03-08 10:46 UTC, joakibj requested changes

2023-03-08 10:46 UTC, joakibj commented on app/src/main/java/no/nav/dokdistdpi/Application.java
> +		DokdistdpiProperties.class,
Pass på at case er endret i git også slik at windows brukere ikke får problemer

2023-03-08 10:46 UTC, joakibj commented on nais/q2-config.json
>    "DOKDISTDPI_PROXY_HOST": "webproxy.nais",
Denne kan vel også fjernes hvis config kommer gjennom system props fra baseimage

2023-03-08 10:46 UTC, joakibj commented on nais/p-config.json
>    "DOKDISTDPI_PROXY_HOST": "webproxy.nais",
Proxy setting kan fjernes siden det ikke settes eksplisitt lenger

2023-03-08 10:46 UTC, joakibj commented on qdist011/src/main/java/no/nav/dokdistdpi/qdist011/Qdist011Route.java
> +						.to("direct:" + OPPDATER_DIGITALPOST_INFO, "direct:" + OPPDATER_VARSELINFO)
Pass på å teste i miljø med parallel processing. Siden den skriver updates til dokdist db så er det risiko for at man får lost writes. Mener at oppdaterVarselInfo kun skriver nye rows i egen tabell og ikke rører de andre så regner med at det skal gå greit men noe man burde passe på generelt. Spesielt hvis man skriver updates til samme tabell

2023-03-08 10:46 UTC, joakibj commented on qdist011/src/test/java/no/nav/dokdistdpi/qdist011/itest/Qdist011IT.java
> -	private Queue backoutQueue;
Ingen tester som sjekker backoutQueue ?

2023-03-08 10:46 UTC, joakibj commented on qdist011/src/main/java/no/nav/dokdistdpi/qdist011/Qdist011Route.java
> +						.multicast().parallelProcessing()
Husk at for parallel processing så kan man miste MDC info som lå på tråden, da vil ikke callId propageres til de nye trådene uten at man gjør noe

2023-03-08 10:46 UTC, joakibj commented on core/src/main/java/no/nav/dokdistdpi/common/NavHeadersFilter.java
> +			return next.exchange(ClientRequest.from(request).headers((headers) -> headers.set(NAV_CALL_ID, MDC.get(CALL_ID))).build());
Ser at `NAV_CALL_ID` er `Nav-Call-Id`. For våre apper skal det være `Nav-Callid`. For digdir-krr-proxy er det sannsynligvis riktig. Dette må sjekkes

2023-03-08 12:20 UTC, tsigab commented on nais/p-config.json
>    "DOKDISTDPI_PROXY_HOST": "webproxy.nais",
Proxy host og port fjernet,

2023-03-08 12:25 UTC, tsigab commented on qdist011/src/main/java/no/nav/dokdistdpi/qdist011/Qdist011Route.java
> +						.to("direct:" + OPPDATER_DIGITALPOST_INFO, "direct:" + OPPDATER_VARSELINFO)
Dette implementasjonen var endret. Det er brukt en metode for oppdaterVarselInfo og updateStatusDigitalLeverandoerAndPostkasseadresse og kalt metoden i Qdist011.

2023-03-08 12:25 UTC, tsigab commented on qdist011/src/test/java/no/nav/dokdistdpi/qdist011/itest/Qdist011IT.java
> -	private Queue backoutQueue;
Det la til en test for backoutQueue.

2023-03-08 12:34 UTC, tsigab commented on core/src/main/java/no/nav/dokdistdpi/common/NavHeadersFilter.java
> +			return next.exchange(ClientRequest.from(request).headers((headers) -> headers.set(NAV_CALL_ID, MDC.get(CALL_ID))).build());
digdir-krr-proxy bruker Nav-Call-Id og byttet callId her til _NAV_CALLID ( Nav-Callid)_

2023-03-08 16:33 UTC, joakibj approved these changes
Ser stort sett greit ut men må testes

2023-03-08 16:33 UTC, joakibj commented on core/src/main/java/no/nav/dokdistdpi/utils/DokdistdpiConstant.java
> +	public static final String NAV_CALLID = "Nav-Callid";
Kan skrive noe om hvor de forskjellige brukes

2023-03-08 16:33 UTC, joakibj commented on qdist011/src/test/java/no/nav/dokdistdpi/qdist011/itest/Qdist011IT.java
> +		await().atMost(100, TimeUnit.SECONDS).untilAsserted(() -> {
100s burde ikke være nødvendig for dette, da er noe annet galt

2023-03-08 17:25 UTC, tsigab commented on nais/q2-config.json
>    "DOKDISTDPI_PROXY_HOST": "webproxy.nais",
Proxy fjernet.

2023-03-08 17:49 UTC, tsigab commented on core/src/main/java/no/nav/dokdistdpi/utils/DokdistdpiConstant.java
> +	public static final String NAV_CALLID = "Nav-Callid";
Problemet her er at det er ikke noe standard callId og i teamet våre for eksempler bruker vi _Nav-CallId_ og _callId_. Eller vi bør ha standard i teamet og kan endre alle våre apper til en standard MDC callId.

2023-03-08 17:54 UTC, tsigab commented on core/src/main/java/no/nav/dokdistdpi/utils/DokdistdpiConstant.java
> +	public static final String NAV_CALLID = "Nav-Callid";
Så endret alle med `callId` til `Nav-CallId`.

2023-03-10 05:48 UTC, merged