MMA-6697 implementert oppdaterforsendelse endepunkt
navikt/dokdistdpi-2 pull request #69
Opened 2023-04-27 12:23 UTC by tsigab

2023-04-28 14:14 UTC, ctumyr requested changes
Noen småting, ellers ser det bra ut 👍

2023-04-28 14:14 UTC, ctumyr commented on core/src/main/java/no/nav/dokdistdpi/consumer/rdist001/domain/OppdaterForsendelseRequest.java
> +public class OppdaterForsendelseRequest {
Ser det allerede eksisterer en klasser som heter `OppdaterForsendelseRequestTo`, den kan kanskje slettes eller brukes i stedet for denne?

2023-04-28 14:14 UTC, ctumyr commented on core/src/main/java/no/nav/dokdistdpi/consumer/rdist001/domain/OppdaterForsendelseRequest.java
> +	private VarselStatusCode varselStatus;
Dette feltet ser ikke ut til å bli brukt. Hvis det kan fjernes kan kanskje tilhørende enum også fjernes.

2023-04-28 14:14 UTC, ctumyr commented on core/src/main/java/no/nav/dokdistdpi/consumer/rdist001/kodeverk/VarselStatusCode.java
> +public enum VarselStatusCode {
Denne kan slettes dersom tidligere kommentar angående feltet i `OppdaterForsendelseRequest` tas til følge.

2023-04-28 14:14 UTC, ctumyr commented on qdist011/src/main/java/no/nav/dokdistdpi/qdist011/Qdist011Service.java
> +		Long forsendelseId = Long.valueOf(distribuerTilKanal.getForsendelseId());
Er det mulig at `distribuerTilKanal.getForsendelseId()` ikke returnerer et gyldig tall? Kunne kanskje forbedra valideringen der isf

2023-05-02 09:14 UTC, tsigab commented on core/src/main/java/no/nav/dokdistdpi/consumer/rdist001/kodeverk/VarselStatusCode.java
> +public enum VarselStatusCode {
Dette slettet.

2023-05-02 09:21 UTC, tsigab commented on qdist011/src/test/java/no/nav/dokdistdpi/qdist011/itest/Qdist011IT.java
> +		await().atMost(100, TimeUnit.SECONDS).untilAsserted(() -> {
10sec er nok men dette har endret i debugging. Den spolte tilbake til forrige verdien.

2023-05-02 09:23 UTC, tsigab commented on core/src/main/java/no/nav/dokdistdpi/consumer/rdist001/DokdistadminConsumer.java
> +		log.info("hentForsendelse mottatt kall til å hente forsendelse med forsendelseId={}", forsendelseId);
Fikset.

2023-05-02 09:24 UTC, tsigab commented on core/src/main/java/no/nav/dokdistdpi/consumer/rdist001/domain/OppdaterForsendelseRequest.java
> +	private VarselStatusCode varselStatus;
Ja, Det er ikke i brukt og fjernet fra klasset.

2023-05-02 11:02 UTC, tsigab commented on qdist011/src/main/java/no/nav/dokdistdpi/qdist011/Qdist011Service.java
> +		Long forsendelseId = Long.valueOf(distribuerTilKanal.getForsendelseId());
Det er [XSD](https://github.com/navikt/melding-virksomhet-dokdistfordeling/blob/master/src/main/resources/no/nav/meldinger/virksomhet/dokdistfordeling/xsd/qdist008/out/distribuertilkanal.xsd) valideringen som mange apper som bruker.  Det trenges en sak til å endre type til tall.

2023-05-02 11:02 UTC, tsigab commented on core/src/main/java/no/nav/dokdistdpi/consumer/rdist001/DokdistadminConsumer.java
> +		log.info("forsendelse med forsendelseId={} mottatt kall til å oppdatere forsendelseStatus={}, digitalLeverandoeradresse og digitalPostkasseadresse",
Fikset.

2023-05-04 09:16 UTC, ctumyr approved these changes
Noen småting, ellers ser det bra ut 👍

2023-05-04 09:16 UTC, ctumyr commented on core/src/main/java/no/nav/dokdistdpi/consumer/rdist001/DokdistadminConsumer.java
> +		log.info("hentForsendelse blir mottatt et kall til å hente forsendelse med forsendelseId={}", forsendelseId);
```suggestion
		log.info("hentForsendelse henter forsendelse med forsendelseId={}", forsendelseId);
```

2023-05-04 09:16 UTC, ctumyr commented on core/src/main/java/no/nav/dokdistdpi/consumer/rdist001/DokdistadminConsumer.java
>  				oppdaterForsendelseRequest.getForsendelseId(), oppdaterForsendelseRequest.getForsendelseStatus());
```suggestion
		log.info("oppdaterForsendelse oppdaterer forsendelseStatus={}, digitalLeverandoeradresse og digitalPostkasseadresse for forsendelse med forsendelseId={}",
		oppdaterForsendelseRequest.getForsendelseStatus(), oppdaterForsendelseRequest.getForsendelseId());
```

2023-05-04 09:16 UTC, ctumyr commented on core/src/main/java/no/nav/dokdistdpi/consumer/rdist001/DokdistadminConsumer.java
> +		log.info("forsendelse med forsendelseId={} blir mottatt et kall til å oppdatere forsendelseStatus={}, digitalLeverandoeradresse og digitalPostkasseadresse",
Gjerne legg til en logg linje etter kallet er ferdig. Feks 

```
log.info("oppdaterForsendelse har oppdatert forsendelse med forsendelseId={}", oppdaterForsendelseRequest.getForsendelseId());
```

2023-05-04 11:46 UTC, tsigab commented on core/src/main/java/no/nav/dokdistdpi/consumer/rdist001/DokdistadminConsumer.java
> +		log.info("hentForsendelse blir mottatt et kall til å hente forsendelse med forsendelseId={}", forsendelseId);
Fikset.

2023-05-04 11:46 UTC, tsigab commented on core/src/main/java/no/nav/dokdistdpi/consumer/rdist001/DokdistadminConsumer.java
>  				oppdaterForsendelseRequest.getForsendelseId(), oppdaterForsendelseRequest.getForsendelseStatus());
Dette fikset.

2023-05-04 11:46 UTC, tsigab commented on core/src/main/java/no/nav/dokdistdpi/consumer/rdist001/DokdistadminConsumer.java
> +		log.info("forsendelse med forsendelseId={} blir mottatt et kall til å oppdatere forsendelseStatus={}, digitalLeverandoeradresse og digitalPostkasseadresse",
Dette fikset.

2023-05-04 11:47 UTC, merged