Mma 7099 vedleggsnummerering dersom duplikate tittler eksisterer
navikt/dokdistdpi-2 pull request #87
Opened 2023-10-27 13:59 UTC by L145025

2023-10-30 10:57 UTC, joakibj requested changes

2023-10-30 10:57 UTC, joakibj commented on qdist011/src/main/java/no/nav/dokdistdpi/qdist011/Qdist011Service.java
> +		if (vedleggList.size() != vedleggList.stream().collect(Collectors.groupingBy(DpiDokument::getTittel)).size()) {
Hva skjer hvis vedlegg 2 og 3 har duplikat tittel men vedlegg 1 har ikke det?

2023-10-30 10:57 UTC, joakibj commented on qdist011/src/main/java/no/nav/dokdistdpi/qdist011/Qdist011Service.java
> +					vedlegg.setTittel(String.format("%s (%s)", vedlegg.getTittel(), vedleggNummer.getAndIncrement()))
Anbefaler ikke å mutere tittel på eksisterende objekt
Ta heller å se på å endre mappingen i `JournalpostQdist011Mapper`. Så er det mye lettere å teste også pga input -> output

2023-10-30 10:57 UTC, joakibj commented on qdist011/src/test/java/no/nav/dokdistdpi/qdist011/Qdist011ServiceTest.java
> +	void skalNavngiVedleggMedTilleggsnummer() {
Ønsker heller en test i `Qdist011IT`

2023-11-02 09:36 UTC, L145025 commented on qdist011/src/main/java/no/nav/dokdistdpi/qdist011/Qdist011Service.java
> +					vedlegg.setTittel(String.format("%s (%s)", vedlegg.getTittel(), vedleggNummer.getAndIncrement()))
Har endret til å endre titttel i mappingen.

2023-11-02 09:39 UTC, L145025 commented on qdist011/src/test/java/no/nav/dokdistdpi/qdist011/Qdist011ServiceTest.java
> +	void skalNavngiVedleggMedTilleggsnummer() {
Usikker på hvordan jeg verifiserer i Itest, men jeg har endret happypath slik at det er to vedlegg med samme tittel som får endret navn.

2023-11-03 10:31 UTC, joakibj approved these changes
Ser godt nok ut

2023-11-03 10:31 UTC, joakibj commented on qdist011/src/main/java/no/nav/dokdistdpi/qdist011/Qdist011Service.java
> +			return null;
Returner en tom `Map` her, f.eks `Map.of()`
Da slipper man å bekymre seg for null sjekker på det senere

2023-11-03 12:33 UTC, merged