MMA-6697 oppdatert virksomhetssertifikat script og endret maskinporte…
navikt/dokdistdpi-2 pull request #90
Opened 2023-11-03 13:24 UTC by tsigab

…n til å bruke default nais config

2023-11-06 12:57 UTC, joakibj requested changes
Har du husket å legge til public keys i maskinporten klienten?

2023-11-06 13:58 UTC, ctumyr commented on core/src/main/java/no/nav/dokdistdpi/consumer/dpi/maskineporten/MaskinportenTokenConsumer.java
> +				.audience(maskinportenProperties.getIssuer())
Stussa også litt på det, men tror det blir riktig. Se https://doc.nais.io/security/auth/maskinporten/client/?h=maskinporten#21-create-jwt-grant

2023-11-07 08:39 UTC, tsigab commented on core/src/main/java/no/nav/dokdistdpi/consumer/dpi/maskineporten/MaskinportenTokenConsumer.java
> +				.audience(maskinportenProperties.getIssuer())
Dette bruker nais maskinporten config og ser linken.

2023-11-07 08:40 UTC, tsigab commented on qdist011/src/test/resources/application-itest.properties
> +maskinporten.clientJwk={"use": "sig", "kty": "RSA", "kid": "4723a1b1-b908-4c6d-980f-0e81ef605acc", "alg": "RS256", "n": "v8JuO3NW2aV5ckwfd4K5hohjXZu8BoewqoJiDlwIqJQSKJ_ByPqfj3GRj8hyjIKnl3kQCF2mFklaIj
JWT token generert fra test sertifikat.

2023-11-07 08:41 UTC, tsigab commented on core/src/main/java/no/nav/dokdistdpi/config/prop/MaskinportenProperties.java
> +	private String issuer;
Implementasjonen endret til å bruke default nais maskinporten config.

2023-11-07 13:03 UTC, joakibj commented on qdist011/src/test/resources/application-itest.properties
> +maskinporten.clientJwk={"use": "sig", "kty": "RSA", "kid": "4723a1b1-b908-4c6d-980f-0e81ef605acc", "alg": "RS256", "n": "v8JuO3NW2aV5ckwfd4K5hohjXZu8BoewqoJiDlwIqJQSKJ_ByPqfj3GRj8hyjIKnl3kQCF2mFklaIj
Denne går ut på tid ikkesant?

2023-11-07 13:21 UTC, joakibj approved these changes
OK avklart at denne burde være i orden, har bare spørsmål på testdata her og ser bygget ikke kjører

2023-11-08 07:54 UTC, merged